name: fsae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1
  - aom=3.9.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.0
  - certifi=2025.10.5
  - charset-normalizer=3.4.3
  - contourpy=1.2.0
  - cycler=0.11.0
  - cython=3.1.4
  - dav1d=1.2.1
  - expat=2.6.3
  - filelock=3.13.1
  - fluidsynth=2.3.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.13.3
  - fsspec=2024.6.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - graphite2=1.3.14
  - grpcio=1.62.2
  - harfbuzz=10.2.0
  - icu=73.2
  - importlib-metadata=8.7.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=21.1.2
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.82.2
  - libgrpc=1.62.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - libmad=0.15.1b
  - libmagic=5.46
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.50
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown=3.9
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mpg123=1.32.8
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.4
  - opusfile=0.12
  - packaging=24.1
  - pcre2=10.44
  - pip=24.2
  - pixman=0.43.4
  - polars=1.10.0
  - portaudio=19.6.0
  - portmidi=2.0.4
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycocotools=2.0.10
  - pygame=2.6.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.4.0
  - pytz=2024.1
  - pyyaml=6.0.3
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - sdl2=2.30.7
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.22.0
  - setuptools=75.1.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.2
  - svt-av1=2.3.0
  - sympy=1.13.2
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - termcolor=3.1.0
  - terminaltables=3.1.10
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tornado=6.4.1
  - tzdata=2024b
  - unicodedata2=15.1.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.2.0
      - arel==0.4.0
      - async-asgi-testclient==1.4.11
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - cacheout==0.14.1
      - cachetools==5.5.0
      - click==8.3.0
      - debugpy==1.8.17
      - distinctipy==1.3.4
      - executing==2.2.1
      - fastapi==0.109.0
      - ffmpeg-python==0.2.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - giturlparse==0.12.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.27.2
      - hyperframe==6.1.0
      - idna==3.10
      - imutils==0.5.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.9.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - numerize==0.12
      - opencv-python==4.11.0.86
      - pandas==2.1.4
      - pillow==10.4.0
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptable==0.9.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydicom==2.4.4
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynrrd==0.4.3
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-multipart==0.0.12
      - referencing==0.36.2
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - shapely==2.0.2
      - simpleitk==2.4.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.35.1
      - stringcase==1.2.0
      - supervisely==6.73.451
      - tqdm==4.67.1
      - trimesh==4.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.2.3
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - varname==0.15.0
      - watchfiles==1.1.0
      - websockets==13.1
      - zstd==1.5.7.2
prefix: /Users/daniel/anaconda3/envs/fsae
