name: fsae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - blas=1.0=openblas
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=hc6c324b_2
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.1.4=py312hd9aa7d2_2
  - dav1d=1.2.1=h80987f9_0
  - expat=2.6.3=h313beb8_0
  - filelock=3.13.1=py312hca03da5_0
  - fluidsynth=2.3.7=h80fea77_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h1383a14_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py312h80987f9_0
  - freetype=2.13.3=hce30654_1
  - fsspec=2024.6.1=py312hca03da5_0
  - gettext=0.22.5=h8414b35_3
  - gettext-tools=0.22.5=h8414b35_3
  - giflib=5.2.2=h93a5062_0
  - graphite2=1.3.14=hc377ac9_1
  - grpcio=1.62.2=py312h17030e7_0
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.2=hc8870d7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.4=py312hca03da5_1
  - joblib=1.4.2=py312hca03da5_0
  - kiwisolver=1.4.4=py312h313beb8_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libasprintf=0.22.5=h8414b35_3
  - libasprintf-devel=0.22.5=h8414b35_3
  - libavif16=1.1.1=h45b7238_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.6.3=hf9b8971_0
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.3=hb765f3a_0
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgettextpo=0.22.5=h8414b35_3
  - libgettextpo-devel=0.22.5=h8414b35_3
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.82.2=hdff4504_1
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.22.5=h8414b35_3
  - libintl-devel=0.22.5=h8414b35_3
  - libjpeg-turbo=3.0.3=h80987f9_0
  - libmad=0.15.1b=h1a8c8d9_1001
  - libmagic=5.46=h93a6450_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h3783ad8_0
  - libprotobuf=4.25.3=hc39d83c_1
  - libre2-11=2023.09.01=h7b2c953_2
  - libsndfile=1.2.2=h9739721_1
  - libsqlite=3.45.2=h091b4b1_0
  - libtiff=4.7.0=hfce79cd_1
  - libvorbis=1.3.7=h1a28f6b_0
  - libwebp=1.5.0=h1618228_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=h3fc13f7_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.9=pyhd8ed1ab_0
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib=3.9.2=py312hca03da5_0
  - matplotlib-base=3.9.2=py312h2df2da3_0
  - mpg123=1.32.8=h57444dd_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.3=py312hca03da5_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.5.4=h5503f6c_0
  - opusfile=0.12=h5643135_2
  - packaging=24.1=py312hca03da5_0
  - pcre2=10.44=ha881caa_2
  - pip=24.2=py312hca03da5_0
  - pixman=0.43.4=hebf3989_0
  - polars=1.10.0=py312h4b5da93_0
  - portaudio=19.6.0=h313beb8_5
  - portmidi=2.0.4=h13dd4ca_2
  - pthread-stubs=0.3=h1a28f6b_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycocotools=2.0.10=py312he0011b7_0
  - pygame=2.6.1=py312hb14fe3b_0
  - pyparsing=3.1.2=py312hca03da5_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.0=py3.12_0
  - pytz=2024.1=py312hca03da5_0
  - pyyaml=6.0.3=py312h5748b74_0
  - rav1e=0.6.6=h69fbcac_2
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h1a28f6b_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py312hd77ebd4_0
  - scipy=1.13.1=py312ha409365_0
  - sdl2=2.30.7=hf9b8971_0
  - sdl2_image=2.8.2=h376e2e1_1
  - sdl2_mixer=2.6.3=h4fe3bdc_1
  - sdl2_ttf=2.22.0=hda0f12e_2
  - setuptools=75.1.0=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.45.2=hf2abe2d_0
  - svt-av1=2.3.0=hf24288c_0
  - sympy=1.13.2=py312hca03da5_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py312h6f41444_3
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - termcolor=3.1.0=pyhd8ed1ab_0
  - terminaltables=3.1.10=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tk=8.6.13=h5083fa2_1
  - torchaudio=2.4.0=py312_cpu
  - torchvision=0.19.0=py312_cpu
  - tornado=6.4.1=py312h80987f9_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.44.0=py312hca03da5_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.2.0
      - arel==0.4.0
      - async-asgi-testclient==1.4.11
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - cacheout==0.14.1
      - cachetools==5.5.0
      - click==8.3.0
      - debugpy==1.8.17
      - distinctipy==1.3.4
      - executing==2.2.1
      - fastapi==0.109.0
      - ffmpeg-python==0.2.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - giturlparse==0.12.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.27.2
      - hyperframe==6.1.0
      - idna==3.10
      - imutils==0.5.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.9.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - numerize==0.12
      - opencv-python==4.11.0.86
      - pandas==2.1.4
      - pillow==10.4.0
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptable==0.9.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydicom==2.4.4
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynrrd==0.4.3
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-multipart==0.0.12
      - referencing==0.36.2
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - shapely==2.0.2
      - simpleitk==2.4.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.35.1
      - stringcase==1.2.0
      - supervisely==6.73.451
      - tqdm==4.67.1
      - trimesh==4.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.2.3
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - varname==0.15.0
      - watchfiles==1.1.0
      - websockets==13.1
      - zstd==1.5.7.2
prefix: /Users/daniel/anaconda3/envs/fsae
